### ISSUE TITLE
Release 2.0.0-beta.3 Developer Checklist

### ISSUE THREAD

**Issue by joe-taylor** [bcgov/ckan-ui#574]
- [x] Bump version in package.json
- [x] Update changelog
- [x] Config update to `ckan.auth.roles_that_cascade_to_sub_groups` for editor
- [x] Migrate changes to beta
- [x] Rerun cat jenkins job after making config change above
- [x] Ensure correct version of helm chart is used
- [x] Discuss and test aforementioned config update with team
- [x] Remove admin key from OCP BuildConfig for bcgov#553
- [x] Confirm that the about page content is ready to be published to beta
