### ISSUE TITLE
Release 2.0.0-beta.8 Developer Checklist

### ISSUE THREAD

**Issue by joe-taylor** [bcgov/ckan-ui#580]
**Test:**

- [x] create release branch release/2.0.0-beta.8
- [x] update test pipeline to pull from this release branch
- [x] bump version number
- [x] ensure changelog is updated for all tickets

**Beta:**

- [x] run jenkins job to migrate any api bug fixes
- [x] merge to master
- [x] reindex
- [x] pull changelog back to dev

**Comment by joe-taylor** [comment]
Skipped 4-7 to align release numbering with changelog.
