### ISSUE TITLE
Developer Checklist - Release 2.0.0-beta.9

### ISSUE THREAD

**Issue by joe-taylor** [bcgov/ckan-ui#602]
**Test**

- [x] create release branch
- [x] bump version in package.json
- [x] update test builds to pull from release branch

**Beta**

- [ ] migrate api changes to beta
- [ ] migrate ui changes to beta
- [ ] update release date in changelog, once known
